# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logfire < Formula
  desc "Logfire command line interface"
  homepage "https://github.com/logfire-sh/cli"
  version "3.5"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/logfire-sh/cli/releases/download/v3.5/logfire_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d6107b5462f7cb8238c4b83dd20eb88370e836698fad6831d2e1f43ea9e03163"

      def install
        bin.install "logfire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logfire-sh/cli/releases/download/v3.5/logfire_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "13fa8e7d9706b8132ab7224852ff0631e2ee1a552f4f5a98f56825e68b8b58ad"

      def install
        bin.install "logfire"
      end
    end
  end

  test do
    system "#{bin/logfire}"
  end
end
