# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logfire < Formula
  desc "Logfire command line interface"
  homepage "https://github.com/logfire-ai/cli"
  version "1.6.2"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/logfire-ai/cli/releases/download/v1.6.2/logfire_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "67ab65fcc0fb8c726e337421a2a624f51dc30300f8a374ca71b8441b7c6e3cf6"

      def install
        bin.install "logfire"
      end
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/logfire-ai/cli/releases/download/v1.6.2/logfire_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7a415f02310aa3ace714b817a4531986807904c660d295418bc49deed979dceb"

        def install
          bin.install "logfire"
        end
      end
    end
  end

  test do
    system "#{bin/logfire}"
  end
end
